---
packetfence_install__centos_release_rpm: 'http://packetfence.org/downloads/PacketFence/RHEL7/packetfence-release-7.devel.noarch.rpm'
packetfence_install__centos:
  repos:
    - packetfence-devel

packetfence_install__deb:
  repos:
    - debian
    - debian-devel
